### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by edent** [synthagency/tumblr-aspartam#1]
I use this theme a lot and would like to help update it. What licence is it under? MIT?
Thanks :-)

**Comment by lucky-yoolk** [comment]
Hi, i have not thinked about that, and to be honest i dont know how to add license :p i added you to collaborators, is that ok for you? :)

**Comment by lucky-yoolk** [comment]
If you make major modifications just let me know ;)

**Comment by edent** [comment]
@synthagency I've updated the theme, cleaned it up, added a licence.  Details at https://github.com/synthagency/tumblr-aspartam/tree/update

Any thoughts?

**Comment by lucky-yoolk** [comment]
Hi, perfect! I dont know how to push this update to the master :-/ could you do it or i have to update files myself? i'll notify tumblr theme garden of the update when done

**Comment by edent** [comment]
Closed via #2
